stages:
  - tests

jobs:
  include:
     - stage: tests
       dist: trusty
       os: linux
       script:
         - set -e

         - cmake -Bbuild -H.

         - git clean -fdxq

         - cmake -Bbuild -H. -DINTEGRATION-TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug
         - cmake --build build --config Debug
         - build/tests/integration/integration-tests

         - git clean -fdxq

         - cmake -Bbuild -H. -DINTEGRATION-TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release
         - cmake --build build --config Release
         - build/tests/integration/integration-tests

         - set +e
