stages:
  - tests (linux, debug, gcc, coverage)
  - tests (osx, release with debug info, clang)

jobs:
  include:
    - stage: tests (linux, debug, gcc, coverage)
      dist: trusty
      os: linux
      env: BUILD_TYPE="Debug"
      before_install:
        - pip install --user cpp-coveralls
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/integration-tests
        - cmake --build build/tests/integration --config $BUILD_TYPE --target check-coverage-files

        - coveralls --gcov-options '\-lp'

        - set +e

    - stage: (osx, release with debug info, clang)
      os: linux
      env: BUILD_TYPE="RelWithDebInfo"
      compiler: clang
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/integration-tests

        - set +e
