git:
    depth: 1

jobs:
  include:
    - name: "tests -- linux, debug, coverage, g++, 64-bit"
      os: linux
      dist: xenial
      language: cpp
      env: BUILD_TYPE="Debug"
      compiler: g++
      before_install:
        - pip install --user cpp-coveralls
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/integration-tests
        - cmake --build build/tests/integration --config $BUILD_TYPE --target check-coverage-files

        - bash <(curl -s https://codecov.io/bash)

        - set +e

    - name: "tests -- osx, release with debug info, clang++, 64-bit"
      os: osx
      osx_image: xcode10.1
      language: cpp
      env: BUILD_TYPE="RelWithDebInfo"
      compiler: clang++
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/integration-tests

        - set +e

    - name: "tests -- windows, release, msvc, 32-bit"
      os: windows
      language: cpp
      env: BUILD_TYPE="Release"
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/$BUILD_TYPE/integration-tests

        - set +e
