stages:
  - tests -- linux, debug, g++, coverage
  - tests -- osx, release with debug info, clang

git:
    depth: 1

jobs:
  include:
    - stage: tests -- linux, debug, gcc, coverage
      dist: trusty
      os: linux
      language: cpp
      env: BUILD_TYPE="Debug"
      compiler: g++
      before_install:
        - pip install --user cpp-coveralls
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/integration-tests
        - cmake --build build/tests/integration --config $BUILD_TYPE --target check-coverage-files

        - bash <(curl -s https://codecov.io/bash)

        - set +e

    - stage: tests -- osx, release with debug info, clang
      os: osx
      language: cpp
      env: BUILD_TYPE="RelWithDebInfo"
      compiler: clang
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
        - cmake --build build/tests/integration --config $BUILD_TYPE
        - build/tests/integration/integration-tests

        - set +e
