stages:
  - generation, tests

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: generation, tests
       dist: trusty
       os: linux
       script:
         - set -e

         - cmake -Bbuild -H. --warn-uninitialized --warn-unused-vars
         - cmake -Bbuild -H. -DRUN_UNIT_TESTS:BOOL=ON -DRUN_INTEGRATION_TESTS:BOOL=ON --warn-uninitialized --warn-unused-vars

         - set +e
