stages:
  - tests (linux, debug, gcc, coverage)
  - tests (osx, release with debug info, clang)

jobs:
  include:
    - stage: tests (linux, debug, gcc, coverage)
      dist: trusty
      os: linux
      before_install:
        - pip install --user cpp-coveralls
      script:
        - set -e

        - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug
        - cmake --build build/tests/integration --config Debug
        - build/tests/integration/integration-tests
        - cmake --build build/tests/integration --config Debug --target check-coverage-files

        - coveralls --gcov-options '\-lp'

        - set +e

     - stage: (osx, release with debug info, clang)
       os: linux
       compiler: clang
       script:
         - set -e

         - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
         - cmake --build build/tests/integration --config RelWithDebInfo
         - build/tests/integration/integration-tests

         - set +e
