stages:
  - tests (osx, debug)
  - tests (linux, release)

jobs:
  include:
     - stage: (linux, release)
       dist: trusty
       os: linux
       script:
         - set -e

         - cmake -Bbuild/tests/integration -Htests/integration -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
         - cmake --build build/tests/integration --config RelWithDebInfo
         - build/tests/integration/integration-tests
         - cmake --build build/tests/integration --config RelWithDebInfo --target check-coverage-files

         - set +e
